spring:
  data:
    redis:
      host: 192.168.169.129
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 8   #连接池最大连接数
          max-wait: -1ms  #连接池最大阻塞时间)(-1没有限制)
          max-idle: 8  #连接池中最大空闲连接
          min-idle: 1  #连接池最小空闲连接
      timeout: PT10S #连接超时时间